language: python
python: 2.7
install:
    - pip install -r requirements.txt
env:
    - OPT=-O2
    - OPT=-Ojit
script: trial typhon && python -m rpython $OPT main
notifications:
    irc: "irc.freenode.org#monte"
